general {
    lock_cmd = pidof hyprlock || hyprlock # Avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # Ensure display is on after waking up
    ignore_dbus_inhibit = false # Respect idle inhibitors from applications like media players
    ignore_systemd_inhibit = false
}

# Dim the screen (optional, if you prefer dimming before full turn off)
listener {
    timeout = 150 # 2.5 minutes
    on-timeout = brightnessctl -s set 10% # Set brightness to minimum (e.g., 10%), avoid 0 for OLED
    on-resume = brightnessctl -r # Restore brightness
}

# Lock the screen
listener {
    timeout = 300 # 5 minutes
    on-timeout = loginctl lock-session # Lock screen when timeout has passed
}

# Turn off the screen completely (recommended for OLED burn-in prevention)
listener {
    timeout = 330 # 5.5 minutes (30 seconds after lock)
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # Screen on and brightness restore
}

# Suspend the system
# listener {
#   timeout = 1800 # 30 minutes
#   on-timeout = systemctl suspend
}
